rvm: 2.2.3
script:
- mkdir -p spec && bundle exec rspec spec
before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
-
before_script:
- psql -c 'create database love_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: cV9cuSz2MERk7ryj5hEagkb61IrXZXF5vJZ9r9j1BW1yzLWCbuczamkWqcow4zT4guPOL9reiU73hTijreP4EX3U0IyR4N0FUScTuM2tofDCjFcV40zPNTaQ0lhh9kjXKhfkT0xz5FTacJQyU0R7/ptuO0JrWOfWNqiHfI+FUDv71+Vky5P7wu4N7VzCVSIaypzot1fAWx/PWRgK8hyotPhol1e0TEzxV5JgjklpZ4/TbpS/KirBlqEwHUlsbslDkCtA0TVZy6n0lcDFCnXNWcHpYFuJesH6dVD95+uygyGMxbTEh6tjvmtr4ipnSpwNWSZKlCqkoeLBG0kxMaijs+nzcgeVE4RBfjHiGQZ+RfVtc1O44jW3eK/CeUX3pz9U4xKsCitY+gWsGNr3YoQmYPQTLL4NA2tKeZSiOpktnSH3fqVWnzdssBCyqpe08wGHq6yTkX3Frq6INWLuC0ihQT2NoyKp8yEsGAYGsR3c8GzT6/zMnIli/zXUi0RO1bg8wpVOq+FS504M3FUiJRlKLt3NlxMd7JK9OzxRw4qjFTzMp1wiEvHrU09KLTmx/7YXysOajp6XP88voUJCoYuLKhzUMIxX3JDnvCc6gbeOwKeiMcrKCFr+DAZuV2TZgg8ZjGY4hIzFwB4jpOwXGlAHuyaE1JDdLfa2i2LA8rhTrdA=
  app:
    staging: loveofbread
